version: '3.7'

services:
  server:
    build:
      context: .
    init: true
    volumes:
      - db:/home/irisowner/conduit/db
      - ./:/home/irisowner/conduit
  web:
    build:
      context: web
      dockerfile: Dockerfile-${web:-vue}
volumes:
  db:
