version: '3.7'

services:
  server:
    build:
      context: .
    init: true
    ports:
      - 52773
    volumes:
      - db:/home/irisowner/conduit/db
      - ./:/home/irisowner/conduit
  web:
    build:
      context: web
      dockerfile: Dockerfile-${web:-vue}
    ports:
      - 80:80
volumes:
  db:
