version: '3.7'
services:
  dev:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    network_mode: service:server
  web:
    network_mode: service:server

