version: '3.7'
services:
  server:
    build:
      context: ..
      args:
        - DEVCONTAINER=true
    init: true
    entrypoint: sleep
    command: infinity
    volumes:
      - db:/home/irisowner/conduit/db
      - ..:/home/irisowner/conduit:cached
  web:
    build:
      context: ../web
      dockerfile: Dockerfile-${web:-vue}
    network_mode: service:server
volumes:
  db:
